{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
    {{- if eq .name "api-gateway" }}
    nodePort: {{ $.Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .name }}
  {{- if eq .name "api-gateway" }}
  type: {{ $.Values.service.type }}
  {{- else }}
  type: ClusterIP
  {{- end }}
{{- end }}