apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}
  labels:
    app: {{ .Chart.Name }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      


